### ISSUE TITLE
java.lang.IllegalStateException: Zero length vector   

### ISSUE THREAD

**Issue by gerka3982** [AlgorithmLX/LGameModpack-Issues#27]
**Description:** Please, provide this description!!!

**Logs:** There your logs from gist.github.com or log file(lasted.log)

Minecraft Version: 1.12.2

Forge Version: there Forge version (example: xx.xx.x.xxx)

Modpack Version: there Modpack version (example: 1.3.10)

//Don't touch me!!!

@AlgorithmLX,
@HollowHorizon

**Comment by Kiri-Yoshikage** [comment]
хоть бы из уважения хоть что-то написал бы... Заполни нормально, а там поговорим

**Comment by gerka3982** [comment]
[22:01:02] [Client thread/ERROR]: ########## GL ERROR ##########
[22:01:02] [Client thread/ERROR]: @ VanillaFix GUI Loop
[22:01:02] [Client thread/ERROR]: 1280: Invalid enum
[22:09:27] [Client thread/ERROR]: Exception when crash menu button clicked:
java.net.SocketException: Unexpected end of file from server
	at sun.net.www.http.HttpClient.parseHTTPHeader(HttpClient.java:792) ~[?:1.8.0_51]
	at sun.net.www.http.HttpClient.parseHTTP(HttpClient.java:647) ~[?:1.8.0_51]
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1535) ~[?:1.8.0_51]
	at sun.net.www.protocol.http.HttpURLConnection.access$200(HttpURLConnection.java:90) ~[?:1.8.0_51]
	at sun.net.www.protocol.http.HttpURLConnection$9.run(HttpURLConnection.java:1432) ~[?:1.8.0_51]
	at sun.net.www.protocol.http.HttpURLConnection$9.run(HttpURLConnection.java:1430) ~[?:1.8.0_51]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_51]
	at java.security.AccessController.doPrivileged(AccessController.java:713) ~[?:1.8.0_51]
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1429) ~[?:1.8.0_51]
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:254) ~[?:1.8.0_51]
	at org.dimdev.utils.HasteUpload.uploadToHaste(HasteUpload.java:32) ~[HasteUpload.class:?]
	at org.dimdev.vanillafix.crashes.GuiProblemScreen.actionPerformed(GuiProblemScreen.java:48) [GuiProblemScreen.class:?]
	at org.dimdev.vanillafix.crashes.GuiCrashScreen.actionPerformed(GuiCrashScreen.java:32) [GuiCrashScreen.class:?]
	at net.minecraft.client.gui.GuiScreen.mouseClicked(GuiScreen.java:443) [blk.class:?]
	at net.minecraft.client.gui.GuiScreen.handleMouseInput(GuiScreen.java:533) [blk.class:?]
	at net.minecraft.client.gui.GuiScreen.handleInput(GuiScreen.java:501) [blk.class:?]
	at net.minecraft.client.Minecraft.runGUILoop(Minecraft.java:4024) [bib.class:?]
	at net.minecraft.client.Minecraft.displayCrashScreen(Minecraft.java:4080) [bib.class:?]
	at net.minecraft.client.Minecraft.run(Minecraft.java:3957) [bib.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:123) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]

**Comment by AlgorithmLX** [comment]
Отказано, закрыто
